// נתוני תוכניות חשמל – עודכן לאחרונה: אפריל 2025
// מקור: kamaze.co.il
const PLANS_LAST_UPDATED = 'אפריל 2025';
const PLANS = [
  {
    "id": "iec_base",
    "company": "חברת החשמל",
    "planName": "תעריף ביתי בסיסי",
    "discountType": "none",
    "discountPercent": 0,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "תעריף ביתי רגיל של חברת החשמל – נקודת ייחוס להשוואה",
    "link": "https://www.iec.co.il",
    "isBaseline": true
  },
  {
    "id": "cellcom_small_bill",
    "company": "סלקום אנרג'י",
    "planName": "חשבון קטן הנחה גדולה",
    "discountType": "fixed",
    "discountPercent": 5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה של 5%–10% בכל שעות היממה, בכל ימות השבוע. אחוז ההנחה משתנה מחודש לחודש לפי גובה הצריכה (מוצג כאן כ-5% – הנחה מינימלית)",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "cellcom_day",
    "company": "סלקום אנרג'י",
    "planName": "חוסכים ביום",
    "discountType": "time_of_use",
    "discountPercent": 15,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 7,
    "discountHoursEnd": 17,
    "condition": null,
    "notes": "הנחה של 15% בימים א'–ה' בין השעות 07:00–17:00",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "cellcom_family",
    "company": "סלקום אנרג'י",
    "planName": "חוסכים למשפחה",
    "discountType": "time_of_use",
    "discountPercent": 18,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 14,
    "discountHoursEnd": 20,
    "condition": null,
    "notes": "הנחה של 18% בימים א'–ה' בין השעות 14:00–20:00",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "cellcom_night",
    "company": "סלקום אנרג'י",
    "planName": "חוסכים בלילה",
    "discountType": "time_of_use_night",
    "discountPercent": 20,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 23,
    "discountHoursEnd": 7,
    "condition": null,
    "notes": "הנחה של 20% בימים א'–ה' בין השעות 23:00–07:00",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "cellcom_fixed",
    "company": "סלקום אנרג'י",
    "planName": "חוסכים קבוע",
    "discountType": "fixed",
    "discountPercent": 5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה בכל שעות היממה: שנה ראשונה 5%, שנה שנייה ואילך 6% (מוצג כאן כ-5%)",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "cellcom_green50",
    "company": "סלקום אנרג'י",
    "planName": "50% חשמל ירוק",
    "discountType": "fixed",
    "discountPercent": 3,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 3% – 50% מהחשמל מקורות מתחדשים (אנרגיה סולארית)",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "cellcom_green100",
    "company": "סלקום אנרג'י",
    "planName": "100% חשמל ירוק",
    "discountType": "fixed",
    "discountPercent": 1,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 1% – 100% מהחשמל מקורות מתחדשים (אנרגיה סולארית)",
    "link": "https://www.kamaze.co.il/Companies/82227/Cellcom/electrical-power"
  },
  {
    "id": "bezeq_fixed",
    "company": "בזק אנרג'י",
    "planName": "חוסכים חכם",
    "discountType": "fixed",
    "discountPercent": 6,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 6% בכל שעות היממה, בכל ימות השבוע",
    "link": "https://www.kamaze.co.il/Companies/82260/Bezeq/electrical-power"
  },
  {
    "id": "bezeq_day",
    "company": "בזק אנרג'י",
    "planName": "חוסכים חכם ביום",
    "discountType": "time_of_use",
    "discountPercent": 15,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 7,
    "discountHoursEnd": 17,
    "condition": null,
    "notes": "הנחה של 15% בימים א'–ה' בין השעות 07:00–17:00",
    "link": "https://www.kamaze.co.il/Companies/82260/Bezeq/electrical-power"
  },
  {
    "id": "bezeq_night",
    "company": "בזק אנרג'י",
    "planName": "חוסכים חכם בלילה",
    "discountType": "time_of_use_night",
    "discountPercent": 20,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 23,
    "discountHoursEnd": 7,
    "condition": null,
    "notes": "הנחה של 20% בימים א'–ה' בין השעות 23:00–07:00",
    "link": "https://www.kamaze.co.il/Companies/82260/Bezeq/electrical-power"
  },
  {
    "id": "superpower_power",
    "company": "סופר פאוור (אלקטרה פאוור)",
    "planName": "מסלול POWER",
    "discountType": "fixed",
    "discountPercent": 6.5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 6.5% בכל שעות היממה, בכל ימות השבוע – לכלל הלקוחות",
    "link": "https://www.kamaze.co.il/Companies/82471/supergas-electric/electrical-power"
  },
  {
    "id": "superpower_day",
    "company": "סופר פאוור (אלקטרה פאוור)",
    "planName": "מסלול יום",
    "discountType": "time_of_use",
    "discountPercent": 16,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 7,
    "discountHoursEnd": 17,
    "condition": null,
    "notes": "הנחה של 16% בימים א'–ה' בין השעות 07:00–17:00",
    "link": "https://www.kamaze.co.il/Companies/82471/supergas-electric/electrical-power"
  },
  {
    "id": "superpower_night",
    "company": "סופר פאוור (אלקטרה פאוור)",
    "planName": "מסלול לילה פלוס",
    "discountType": "time_of_use_night",
    "discountPercent": 21,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 23,
    "discountHoursEnd": 7,
    "condition": null,
    "notes": "הנחה של 21% בימים א'–ה' בין השעות 23:00–07:00 – ההנחה הגבוהה ביותר בשוק",
    "link": "https://www.kamaze.co.il/Companies/82471/supergas-electric/electrical-power"
  },
  {
    "id": "superpower_green",
    "company": "סופר פאוור (אלקטרה פאוור)",
    "planName": "מסלול GREEN",
    "discountType": "fixed",
    "discountPercent": 3.5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 3.5% – 100% חשמל ירוק המיוצר בשדות סולריים",
    "link": "https://www.kamaze.co.il/Companies/82471/supergas-electric/electrical-power"
  },
  {
    "id": "hot_247",
    "company": "הוט אנרג'י",
    "planName": "חוסכים 24/7",
    "discountType": "fixed",
    "discountPercent": 5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 5% בכל שעות היממה, בכל ימות השבוע",
    "link": "https://www.kamaze.co.il/Companies/82228/Hot/electrical-power"
  },
  {
    "id": "hot_day",
    "company": "הוט אנרג'י",
    "planName": "חוסכים ביום",
    "discountType": "time_of_use",
    "discountPercent": 15,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 7,
    "discountHoursEnd": 17,
    "condition": null,
    "notes": "הנחה של 15% בימים א'–ה' בין השעות 07:00–17:00",
    "link": "https://www.kamaze.co.il/Companies/82228/Hot/electrical-power"
  },
  {
    "id": "hot_night",
    "company": "הוט אנרג'י",
    "planName": "חוסכים בלילה",
    "discountType": "time_of_use_night",
    "discountPercent": 20,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 23,
    "discountHoursEnd": 7,
    "condition": null,
    "notes": "הנחה של 20% בימים א'–ה' בין השעות 23:00–07:00",
    "link": "https://www.kamaze.co.il/Companies/82228/Hot/electrical-power"
  },
  {
    "id": "hot_fixed_members",
    "company": "הוט אנרג'י",
    "planName": "חוסכים קבוע HOT",
    "discountType": "fixed",
    "discountPercent": 6,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": "רק ללקוחות HOT / HOT mobile / NEXT",
    "notes": "הנחה קבועה של 6% בכל שעות היממה – בלעדי ללקוחות הוט, NEXT או HOT mobile",
    "link": "https://www.kamaze.co.il/Companies/82228/Hot/electrical-power"
  },
  {
    "id": "pazgas_247",
    "company": "פזגז חשמל",
    "planName": "הנחה 24/7",
    "discountType": "fixed",
    "discountPercent": 5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה של 5% בכל ימות השבוע ובכל שעות היממה",
    "link": "https://www.kamaze.co.il/Companies/82476/pazgas-electric/electrical-power"
  },
  {
    "id": "pazgas_yellow",
    "company": "פזגז חשמל",
    "planName": "מסלול צבירה yellow",
    "discountType": "accumulate",
    "discountPercent": 10,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "maxYearlySavings": 600,
    "condition": "דורש חברות באפליקציית yellow של פזגז",
    "notes": "צבירה של 10% מהסכום המשולם עבור צריכת החשמל לארנק באפליקציית yellow, עד 600 ₪ בשנה (50 ₪ בחודש)",
    "link": "https://www.kamaze.co.il/Companies/82476/pazgas-electric/electrical-power"
  },
  {
    "id": "partner_fixed",
    "company": "פרטנר פאוור",
    "planName": "הנחה קבועה כל היום",
    "discountType": "fixed",
    "discountPercent": 5,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה בכל שעות היממה: שנה ראשונה 5%, שנה שנייה 6%, שנה שלישית 7% (מוצג כאן כ-5% – שנה ראשונה). ניתן להצטרף גם ללא מונה חכם",
    "link": "https://www.kamaze.co.il/Companies/82287/Partner/electrical-power"
  },
  {
    "id": "partner_day",
    "company": "פרטנר פאוור",
    "planName": "עובדים מהבית",
    "discountType": "time_of_use",
    "discountPercent": 15,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 7,
    "discountHoursEnd": 17,
    "condition": null,
    "notes": "הנחה של 15% בימים א'–ה' בין השעות 07:00–17:00",
    "link": "https://www.kamaze.co.il/Companies/82287/Partner/electrical-power"
  },
  {
    "id": "partner_night",
    "company": "פרטנר פאוור",
    "planName": "חיות לילה",
    "discountType": "time_of_use_night",
    "discountPercent": 20,
    "discountDays": [0, 1, 2, 3, 4],
    "discountHoursStart": 23,
    "discountHoursEnd": 7,
    "condition": null,
    "notes": "הנחה של 20% בימים א'–ה' בין השעות 23:00–07:00",
    "link": "https://www.kamaze.co.il/Companies/82287/Partner/electrical-power"
  },
  {
    "id": "amisragas_6pct",
    "company": "אמישראגז חשמל",
    "planName": "6% הנחה קבועה",
    "discountType": "fixed",
    "discountPercent": 6,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": null,
    "notes": "הנחה קבועה של 6% בכל שעות היממה, ללא הגבלות שעות – לכלל הלקוחות",
    "link": "https://www.kamaze.co.il/Companies/82501/amisragas--electric/electrical-power"
  },
  {
    "id": "amisragas_7pct",
    "company": "אמישראגז חשמל",
    "planName": "7% הנחה קבועה ללקוחות אמישראגז",
    "discountType": "fixed",
    "discountPercent": 7,
    "discountDays": [],
    "discountHoursStart": null,
    "discountHoursEnd": null,
    "condition": "רק ללקוחות גז של אמישראגז",
    "notes": "הנחה קבועה של 7% בכל שעות היממה, ללא הגבלות שעות – בלעדי ללקוחות הגז הקיימים של אמישראגז",
    "link": "https://www.kamaze.co.il/Companies/82501/amisragas--electric/electrical-power"
  }
]
;